#!/bin/sh

set -e

cd "$(dirname "$0")/.."

script/update

brew services restart postgres

source venv/bin/activate

export ENV=development

export DATABASE_URL=postgres://localhost/ganttcharts

heroku local
